[versions]
agp = "8.2.0"
activityKtx = "1.8.2"
customQrGeneratorVersion = "1.6.2"
jsonVersion = "20231013"
kotlinxCoroutinesCoreVersion = "1.7.3"
ksp = "1.9.22-1.0.16"
coreVersion = "4.6.2"
andratingbar = "1.0.6"
flexbox = "3.0.0"
concurrentFutures = "1.1.0"
core = "3.4.0"
converterScalars = "2.9.0"
converterGson = "2.9.0"
appcenter = "4.4.5"
constraintlayout = "2.1.4"
compiler = "4.15.1"
glide = "4.15.1"
gson = "2.10.1"
kndroidx = "dc76a654ec"
kotlin = "1.9.22"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
lifecycle = "2.7.0"
material = "1.11.0"
photoview = "2.2.0"
wear = "1.4.0-alpha01"
okio = "3.4.0"
okhttp = "5.0.0-alpha.11"
retrofit = "2.9.0"
recyclerviewExt = "1.3.3"
swiperefreshlayout = "1.1.0"
room = "2.6.1"

[libraries]
alexzhirkevich-custom-qr-generator = { module = "com.github.alexzhirkevich:custom-qr-generator", version.ref = "customQrGeneratorVersion" }
andRatingBar = { module = "com.github.wdsqjq:AndRatingBar", version.ref = "andratingbar" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
core = { module = "com.google.zxing:core", version.ref = "core" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCoreVersion" }
json-json = { module = "org.json:json", version.ref = "jsonVersion" }
microsoft-appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appcenter" }
microsoft-appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appcenter" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "coreVersion" }
kndroidx = { group = "com.github.sky130", name = "kndroidx", version.ref = "kndroidx" }
kndroidx-core = { group = "com.github.kndroidx.kndroidx", name = "core", version.ref = "kndroidx" }
kndroidx-wear-recycler = { group = "com.github.kndroidx.kndroidx", name = "wear-smooth-recycler", version.ref = "kndroidx" }
kndroidx-databinding = { group = "com.github.kndroidx.kndroidx", name = "core-databinding", version.ref = "kndroidx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
recyclerview-ext = { module = "com.loongwind.ardf:recyclerview-ext", version.ref = "recyclerviewExt" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "kotlin-kapt" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }


