[versions]
agp = "8.13.2"
brv = "1.6.1"
gridlayout = "1.1.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinpoet = "2.2.0"
kotlinpoetKsp = "2.2.0"
kotlinxSerializationJson = "1.10.0-RC"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
horologistTilesVersion = "0.7.15"
guavaVersion = "33.5.0-android"
horologistComposeToolsVersion = "0.7.15"
ksp = "2.3.4"
activityKtx = "1.12.2"
customQrGeneratorVersion = "1.6.2"
jsonVersion = "20251224"
kotlinxCoroutinesCoreVersion = "1.10.2"
coreVersion = "4.6.2"
andratingbar = "1.0.6"
flexbox = "3.0.0"
concurrentFutures = "1.3.0"
core = "3.5.4"
retrofit-converter = "3.0.0"
koin-bom = "4.1.1"
appcenter = "5.0.6"
compiler = "5.0.5"
glide = "5.0.5"
gson = "2.13.2"
kndroidx = "3135fe1501"
lifecycle = "2.10.0"
photoview = "2.2.0"
protolayout = "1.3.0"
resultat = "1.0.0"
symbolProcessingApi = "2.3.4"
tiles = "1.5.0"
wear = "1.4.0-beta01"
okio = "3.16.4"
okhttp = "5.3.2"
retrofit = "3.0.0"
recyclerviewExt = "1.3.3"
swiperefreshlayout = "1.2.0"
room = "2.8.4"
cardview = "1.0.0"
jetbrainsKotlinJvm = "2.3.0"
miwu="3.0.0"
roomCommonJvm = "2.8.4"
recyclerview="1.4.0"
tilesToolingPreview = "1.5.0"
tilesTooling = "1.5.0"
#noinspection NewerVersionAvailable
slf4jApi = "2.0.7"
logbackAndroid = "3.0.0"
kotlinStdlib = "2.3.0"
kotlinTest = "2.2.0"
runner = "1.5.2"
androidxCore = "1.7.0"

[libraries]
alexzhirkevich-custom-qr-generator = { module = "com.github.alexzhirkevich:custom-qr-generator", version.ref = "customQrGeneratorVersion" }
andRatingBar = { module = "com.github.wdsqjq:AndRatingBar", version.ref = "andratingbar" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-protolayout = { module = "androidx.wear.protolayout:protolayout", version.ref = "protolayout" }
androidx-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "tiles" }
brv = { module = "com.github.liangjingkanji:BRV", version.ref = "brv" }
converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit-converter" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
core = { module = "com.google.zxing:core", version.ref = "core" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-bom" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin-bom" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-bom" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-bom" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-bom" }

androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit-converter" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-converter" }
google-horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologistTilesVersion" }
google-guava = { module = "com.google.guava:guava", version.ref = "guavaVersion" }
google-horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologistComposeToolsVersion" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCoreVersion" }
json-json = { module = "org.json:json", version.ref = "jsonVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
resultat = { module = "fr.haan.resultat:resultat", version.ref = "resultat" }
square-kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
microsoft-appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appcenter" }
microsoft-appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appcenter" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "coreVersion" }
kndroidx = { group = "com.github.sky130", name = "kndroidx", version.ref = "kndroidx"}
kndroidx-core = { group = "com.github.sky130.kndroidx", name = "core", version.ref = "kndroidx" }
kndroidx-wear-recycler = { group = "com.github.sky130.kndroidx", name = "wear-smooth-recycler", version.ref = "kndroidx" }
kndroidx-databinding = { group = "com.github.sky130.kndroidx", name = "core-databinding", version.ref = "kndroidx" }
kndroidx-recycler-databinding = { group = "com.github.sky130.kndroidx", name = "recycler-databinding", version.ref = "kndroidx" }
kndroidx-wear-tile = { group = "com.github.sky130.kndroidx", name = "wear-tile", version.ref = "kndroidx" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-jetbrains-kotlinx-kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesCoreVersion" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "protolayout" }
protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "protolayout" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
recyclerview-ext = { module = "com.loongwind.ardf:recyclerview-ext", version.ref = "recyclerviewExt" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
squareup-kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-tiles-tooling-preview = { group = "androidx.wear.tiles", name = "tiles-tooling-preview", version.ref = "tilesToolingPreview" }
androidx-tiles-tooling = { group = "androidx.wear.tiles", name = "tiles-tooling", version.ref = "tilesTooling" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "androidxCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "kotlin-kapt" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }


