[versions]
agp = "8.13.2"
brv = "1.6.1"
gridlayout = "1.1.0"
kotlin = "2.3.0"
androidx-core-ktx = "1.17.0"
junit = "4.13.2"
androidx-junit = "1.3.0"
androidx-espresso-core = "3.7.0"
androidx-appcompat = "1.7.1"
kotlinpoet = "2.2.0"
kotlinx-serialization-json = "1.10.0-RC"
google-material = "1.13.0"
androidx-activity = "1.12.2"
constraintlayout = "2.2.1"
horologistTilesVersion = "0.7.15"
guavaVersion = "33.5.0-android"
horologistComposeToolsVersion = "0.7.15"
ksp = "2.3.3"
androidx-activity-ktx = "1.12.2"
custom-qr-generator = "1.6.2"
ktor = "3.3.3"
org-json = "20251224"
kotlinx-coroutines-core = "1.10.2"
markwon-core = "4.6.2"
andratingbar = "1.0.6"
google-flexbox = "3.0.0"
concurrentFutures = "1.3.0"
google-zxing-core = "3.5.4"
retrofit-converter = "3.0.0"
koin-bom = "4.1.1"
microsoft-appcenter = "5.0.6"
glidecompiler = "5.0.5"
glide = "5.0.5"
gson = "2.13.2"
kndroidx = "3135fe1501"
androidx-lifecycle = "2.10.0"
androidx-wear-protolayout = "1.3.0"
resultat = "1.0.0"
google-ksp-symbol-processing-api = "2.3.4"
androidx-wear-tiles = "1.5.0"
wear = "1.4.0-beta01"
okio = "3.16.4"
okhttp = "5.3.2"
retrofit = "3.0.0"
androidx-swiperefreshlayout = "1.2.0"
androidx-room = "2.8.4"
androidx-cardview = "1.0.0"
jetbrains-kotlin-jvm = "2.3.0"
miwu = "3.0.0"
androidx-room-common-jvm = "2.8.4"
androidx-recyclerview = "1.4.0"
androidx-wear-tiles-tooling-preview = "1.5.0"
androidx-wear-tiles-tooling = "1.5.0"
#noinspection NewerVersionAvailable
slf4jApi = "2.0.7"
logback-android = "3.0.0"
kotlin-stdlib = "2.3.0"
kotlin-test = "2.2.0"
androidx-test-runner = "1.5.2"
androidx-core = "1.7.0"
ktorfit = "2.7.2"
kotlincrypto-hash = "0.8.0"

[libraries]
# third-party libraries
alexzhirkevich-custom-qr-generator = { module = "com.github.alexzhirkevich:custom-qr-generator", version.ref = "custom-qr-generator" }
andRatingBar = { module = "com.github.wdsqjq:AndRatingBar", version.ref = "andratingbar" }
brv = { module = "com.github.liangjingkanji:BRV", version.ref = "brv" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon-core" }
json = { module = "org.json:json", version.ref = "org-json" }
resultat = { module = "fr.haan.resultat:resultat", version.ref = "resultat" }
kotlincrypto-hash-bom = { module = "org.kotlincrypto.hash:bom", version.ref = "kotlincrypto-hash" }
kotlincrypto-hash-md = { module = "org.kotlincrypto.hash:md" }



# koin libraries
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-bom" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin-bom" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-bom" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-bom" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-bom" }


# microsoft app center
microsoft-appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "microsoft-appcenter" }
microsoft-appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "microsoft-appcenter" }


# glide libraries
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glidecompiler" }


# junit
junit = { group = "junit", name = "junit", version.ref = "junit" }


# androidx libraries
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidx-cardview" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "androidx-room-common-jvm" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-core" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
androidx-wear-protolayout = { module = "androidx.wear.protolayout:protolayout", version.ref = "androidx-wear-protolayout" }
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
androidx-wear-protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "androidx-wear-protolayout" }
androidx-wear-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "androidx-wear-protolayout" }
androidx-wear-tiles-tooling-preview = { group = "androidx.wear.tiles", name = "tiles-tooling-preview", version.ref = "androidx-wear-tiles-tooling-preview" }
androidx-wear-tiles-tooling = { group = "androidx.wear.tiles", name = "tiles-tooling", version.ref = "androidx-wear-tiles-tooling" }


# kndroidx libraries
kndroidx = { group = "com.github.sky130", name = "kndroidx", version.ref = "kndroidx" }
kndroidx-core = { group = "com.github.sky130.kndroidx", name = "core", version.ref = "kndroidx" }
kndroidx-wear-recycler = { group = "com.github.sky130.kndroidx", name = "wear-smooth-recycler", version.ref = "kndroidx" }
kndroidx-databinding = { group = "com.github.sky130.kndroidx", name = "core-databinding", version.ref = "kndroidx" }
kndroidx-recycler-databinding = { group = "com.github.sky130.kndroidx", name = "recycler-databinding", version.ref = "kndroidx" }
kndroidx-wear-tile = { group = "com.github.sky130.kndroidx", name = "wear-tile", version.ref = "kndroidx" }


# logback libraries
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }


# squareup libraries
squareup-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
squareup-retrofit-converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit-converter" }
squareup-retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit-converter" }
squareup-retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-converter" }
squareup-kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }


# google libraries
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologistTilesVersion" }
google-guava = { module = "com.google.guava:guava", version.ref = "guavaVersion" }
google-horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologistComposeToolsVersion" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "google-flexbox" }
google-zxing-core = { module = "com.google.zxing:core", version.ref = "google-zxing-core" }
google-ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "google-ksp-symbol-processing-api" }


# kotlin libraries
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }


ktorfit = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib", version.ref = "ktorfit" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }


ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "kotlin-kapt" }


jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin-jvm" }


kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }

